name: Simple Usage

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: generate HTML
        uses: docker://pandoc/core
        with:
          args: doc.md -o doc.html --embed-resources --standalone --toc --shift-heading-level-by=-1 --template=template.html
      - name: move html file
        run: |
          mkdir -p docs/
          mv doc.html docs/
          ls docs/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment